### ISSUE TITLE
Denormalizer::denormalizeResult returning empty Result

### ISSUE THREAD

**Issue by oakleaf** [jongotlin/ArbetsformedlingenAds#9]
When publishing a new Job, the result from their API is this,

string(26) "{"Message":"Unauthorized"}"

Valid JSON, so that's fine, but it's obviously an error, but the denormalized result doesnt return this, but maybe it should?
https://github.com/jongotlin/ArbetsformedlingenAds/blob/b5d4774802c62d777facb7c0db83820e3eb12f84/src/Denormalizer.php#L25

We could check if $data is an array == errors provided?

If no array == no errors == return Result with message? 

There could be more useful information returned from the Result than just knowing of the errors or not(?)

Other than this, AWESOME library!!

**Comment by jongotlin** [comment]
Thank you.
I'm not using this library anymore and cannot really test it. A PR is more than welcome!

**Comment by drblue** [comment]
> string(26) "{"Message":"Unauthorized"}"

I have a fork of this library where I've added support for returning the error if the response is just a string (no JSON) to account for temporary errors along with a few minor bug fixes. Just added support for "Unauthorized" response and submitted a PR.

**Comment by drblue** [comment]
@oakleaf I have a fork of this library where I've added support for returning the error if the response is just a string (no JSON) to account for temporary errors along with a few minor bug fixes. Just added support for "Unauthorized" response and submitted a [PR](https://github.com/jongotlin/ArbetsformedlingenAds/pull/10).

**Comment by oakleaf** [comment]
Oh, great! I will combine it with my findings as well and ask for a merge a bit later this week :)

**Comment by oakleaf** [comment]
I have added a PR now which includes your changes from that other PR + some minor improvements to Model\Result (It can now return the original response)
